name: Medium Algos Workflow

on: [push, pull_request]

jobs:
  check-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for test folder
        run: |
          if [ ! -d "./test" ]; then
            echo "Test folder not found!"
            exit 1
          fi

      - name: Check for README.md
        run: |
          if [ ! -f "./README.md" ]; then
            echo "README.md file not found!"
            exit 1
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
