name: Check Folder and Files

on: [push, pull_request]

jobs:
  check-folders-and-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for LeeteCode folder
        run: |
          if [ ! -d "Leetecode" ]; then
            echo "Leetecode folder does not exist"
            exit 1
          fi

      - name: Check for Easy, Medium, and Hard folders
        run: |
          for folder in Easy Medium Hard; do
            if [ ! -d "LeeteCode/$folder" ]; then
              echo "LeeteCode/$folder folder does not exist"
              exit 1
            fi
          done

      - name: Check for LICENSE and README files in Algos folder
        run: |
          for file in LICENSE README; do
           if [ ! -f "$file" ]; then
             echo "$file file does not exist in the Algos folder"
             exit 1
           fi
          done
