name: Check Folder and Files

on: [push, pull_request]

jobs:
  check-folders-and-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for LeeteCode folder
        run: |
          if [ ! -d "Leetecode" ]; then
            echo "Leetecode folder does not exist"
            exit 1
          fi

      - name: Check if LeeteCode folder is empty
        run: |
          if [ -z "$(ls -A Leetecode)" ]; then
            echo "Leetecode folder is empty"
            exit 1
          fi

      - name: Check for README.md file and LICENSE file
        run: |
          if [ ! -f "README.md" ]; then
            echo "README.md file does not exist"
            exit 1
          fi
          if [ ! -f "LICENSE" ]; then
            echo "LICENSE file does not exist"
            exit 1
          fi
      - name: Check for .gitignore file
        run: |
          if [ ! -f ".gitignore" ]; then
            echo ".gitignore file does not exist"
            exit 1
          fi

      - name: Run tests in Easy folder
        working-directory: Leetecode/Easy
        run: npm install && npm test

      - name: Run tests in Medium folder
        working-directory: Leetecode/Medium
        run: npm install && npm test

      - name: Run tests in Hard folder
        working-directory: Leetecode/Hard
        run: npm install && npm test
